import { useEffect, useMemo, useState } from 'react'
import PageHeader from '../components/PageHeader.jsx'
import PrintHeader, { PrintSignature } from '../components/PrintHeader.jsx'
import { useData } from '../context/DataContext.jsx'
import { useToast } from '../context/ToastContext.jsx'
import { printPrintArea } from '../lib/printHelper.js'

const KEY='kbc_program_pendampingan_v2'
const kegiatanDefault=[
 {tahap:'Pra-Pendampingan',kegiatan:'Koordinasi pengawas, penetapan madrasah piloting, penyusunan jadwal, dan sosialisasi aplikasi',waktu:'Minggu 0',metode:'Koordinasi/FGD',sasaran:'Pokjawas dan Pengawas',indikator:'Daftar madrasah dan jadwal tersedia',eviden:'Daftar madrasah, jadwal, akun aplikasi'},
 {tahap:'Sosialisasi KBC',kegiatan:'Sosialisasi konsep KBC, Panca Cinta, pembelajaran berbasis cinta, budaya madrasah, dan eviden',waktu:'Minggu 1',metode:'Sosialisasi terarah',sasaran:'Kepala Madrasah, Tim KBC, Guru',indikator:'Pemahaman awal terbentuk',eviden:'Notulen, daftar hadir, materi, dokumentasi'},
 {tahap:'Pemetaan Awal',kegiatan:'Telaah dokumen, wawancara, observasi awal, dan pengisian instrumen kesiapan',waktu:'Minggu 1',metode:'Observasi, wawancara, telaah dokumen',sasaran:'Madrasah Piloting',indikator:'Peta kesiapan tersedia',eviden:'Peta kesiapan dan catatan awal'},
 {tahap:'Pendampingan Perencanaan',kegiatan:'Bimbingan SK Tim KBC, program kerja, jadwal, KOM, dan modul ajar/RPP',waktu:'Minggu 2',metode:'Coaching dan mentoring',sasaran:'Kepala Madrasah, Tim KBC, Guru',indikator:'Dokumen perencanaan tersusun',eviden:'SK Tim, program, jadwal, perangkat ajar'},
 {tahap:'Pendampingan Implementasi',kegiatan:'Observasi pembelajaran, pembiasaan, budaya, kokurikuler/ekstrakurikuler, dan penguatan eviden',waktu:'Minggu 2�3',metode:'Observasi, bimbingan, refleksi',sasaran:'Guru dan warga madrasah',indikator:'KBC tampak dalam pembelajaran dan budaya',eviden:'Catatan observasi dan eviden kegiatan'},
 {tahap:'Monitoring dan Evaluasi',kegiatan:'Pengisian instrumen monitoring, pengolahan skor, diskusi refleksi, dan validasi eviden',waktu:'Minggu 3�4',metode:'Supervisi dan verifikasi',sasaran:'Tim KBC',indikator:'Skor capaian dan kategori tersedia',eviden:'Instrumen, skor, rekomendasi'},
 {tahap:'Tindak Lanjut',kegiatan:'Penyusunan rencana tindak lanjut bersama kepala madrasah dan Tim KBC',waktu:'Minggu 4',metode:'FGD reflektif',sasaran:'Kepala Madrasah dan Tim KBC',indikator:'RTL memiliki PIC dan batas waktu',eviden:'Dokumen RTL'},
 {tahap:'Pelaporan',kegiatan:'Penyusunan laporan per madrasah dan rekap wilayah melalui aplikasi',waktu:'Akhir siklus/semester',metode:'Digitalisasi pelaporan',sasaran:'Pengawas/Admin',indikator:'Laporan lengkap tersedia',eviden:'Laporan pendampingan dan rekap progres'}
];
const defaults={nama:'Program Pendampingan Implementasi Kurikulum Berbasis Cinta',tahun:'2026/2027',semester:'Ganjil',mulai:'',selesai:'',madrasahId:'',latar:'Implementasi Kurikulum Berbasis Cinta memerlukan pendampingan yang terencana, sistematis, dan berkelanjutan agar nilai-nilai cinta terintegrasi dalam tata kelola, budaya madrasah, serta proses pembelajaran.',dasar:'1. UU Nomor 20 Tahun 2003 tentang Sistem Pendidikan Nasional.\\n2. Perpres Nomor 87 Tahun 2017 tentang Penguatan Pendidikan Karakter.\\n3. PMA Nomor 2 Tahun 2020 tentang Penyelenggaraan Penguatan Pendidikan Karakter.\\n4. Perpres Nomor 58 Tahun 2023 tentang Penguatan Moderasi Beragama.\\n5. KMA Nomor 450 Tahun 2024 sebagaimana diperbarui dengan KMA Nomor 1503 Tahun 2025.\\n6. Kepdirjen Pendis Nomor 6077 Tahun 2025 tentang Panduan Kurikulum Berbasis Cinta.\\n7. Program Kerja Pokjawas Madrasah Kabupaten Jember.',tujuanUmum:'Meningkatkan kapasitas madrasah piloting dalam mengimplementasikan KBC secara utuh, terukur, dan berkelanjutan.',tujuanKhusus:'1. Mendampingi penyusunan program dan perangkat KBC.\\n2. Menguatkan budaya madrasah berbasis nilai cinta.\\n3. Meningkatkan kualitas pembelajaran yang mengintegrasikan KBC.\\n4. Memastikan monitoring, eviden, refleksi, dan tindak lanjut berjalan.',kondisi:'Madrasah telah memiliki komitmen awal implementasi KBC, namun masih membutuhkan penguatan perencanaan, perangkat ajar, pelaksanaan, dokumentasi eviden, dan evaluasi.',prioritas:'Perencanaan program; penguatan perangkat ajar; pembiasaan budaya cinta; pendampingan pembelajaran; kelengkapan eviden; monitoring dan refleksi.',sasaran:'Kepala Madrasah, Tim Pelaksana KBC, guru, tenaga kependidikan, dan warga madrasah.',materi:'Konsep KBC; perencanaan program; perangkat ajar; budaya madrasah; pembelajaran; supervisi; eviden; refleksi; tindak lanjut; pelaporan.',strategi:'Coaching, mentoring, konsultasi, FGD, observasi, supervisi, telaah dokumen, refleksi; dilaksanakan secara luring dan/atau daring.',indikator:'1. Program dan Tim KBC terbentuk.\\n2. Perangkat ajar mengintegrasikan nilai KBC.\\n3. Budaya dan pembiasaan KBC terlaksana.\\n4. Eviden setiap kegiatan terdokumentasi.\\n5. Capaian meningkat dan RTL tersedia.',driveUrl:'',kegiatan:kegiatanDefault}
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults}}
const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))

export default function ProgramPendampinganPage(){
 const {state}=useData(),toast=useToast();const [f,setF]=useState(load);const [edit,setEdit]=useState(true)
 const madrasah=state.madrasah.find(m=>m.id===f.madrasahId);const pengawas=state.pengawas?.[0]
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(f)),[f])
 const set=(k,v)=>setF(x=>({...x,[k]:v}));const addRow=()=>set('kegiatan',[...f.kegiatan,{tahap:'',kegiatan:'',waktu:'',metode:'',sasaran:'',indikator:'',eviden:''}]);const row=(i,k,v)=>set('kegiatan',f.kegiatan.map((x,n)=>n===i?{...x,[k]:v}:x))
 const period=useMemo(()=>[f.mulai,f.selesai].filter(Boolean).join(' s.d. ')||'-',[f.mulai,f.selesai])
 const save=()=>{localStorage.setItem(KEY,JSON.stringify(f));setEdit(false);toast.success('Program pendampingan disimpan.')}
 const word=()=>{const el=document.querySelector('.print-area');if(!el)return;const html=`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><style>body{font-family:Arial;font-size:11pt}table{border-collapse:collapse;width:100%}th,td{border:1px solid #333;padding:5px}h1,h2{text-align:center}p{white-space:pre-wrap}</style></head><body>${el.innerHTML}</body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',html],{type:'application/msword'}));a.download='Program-Pendampingan-Pengawas.doc';a.click();URL.revokeObjectURL(a.href);toast.success('Dokumen Word diunduh.')}
 return <><PageHeader title="Program Pendampingan Pengawas" icon="📝" description="Rencana kerja pendampingan madrasah piloting Implementasi KBC." actions={<><button className="btn-ghost" onClick={()=>setEdit(!edit)}>{edit?'👁 Pratinjau':'✎ Edit'}</button><button className="btn-primary" onClick={save}>💾 Simpan</button><button className="btn-ghost" onClick={()=>printPrintArea({title:'Program Pendampingan Pengawas'})}>📄 PDF</button><button className="btn-ghost" onClick={word}>📝 Word</button></>}/>
 {edit&&<div className="space-y-4 mb-6"><Section title="1. Identitas Program"><div className="grid sm:grid-cols-2 gap-3"><Field label="Nama Program" value={f.nama} onChange={v=>set('nama',v)}/><Field label="Madrasah Sasaran" type="select" value={f.madrasahId} onChange={v=>set('madrasahId',v)} options={state.madrasah.map(m=>[m.id,m.nama])}/><Field label="Tahun Pelajaran" value={f.tahun} onChange={v=>set('tahun',v)}/><Field label="Semester" type="select" value={f.semester} onChange={v=>set('semester',v)} options={[['Ganjil','Ganjil'],['Genap','Genap']]}/><Field label="Tanggal Mulai" type="date" value={f.mulai} onChange={v=>set('mulai',v)}/><Field label="Tanggal Selesai" type="date" value={f.selesai} onChange={v=>set('selesai',v)}/></div></Section>
 <Section title="2. Latar Belakang & Dasar Hukum"><Area label="Latar Belakang" value={f.latar} onChange={v=>set('latar',v)}/><Area label="Dasar Hukum" value={f.dasar} onChange={v=>set('dasar',v)}/></Section>
 <Section title="3. Tujuan Pendampingan"><Area label="Tujuan Umum" value={f.tujuanUmum} onChange={v=>set('tujuanUmum',v)}/><Area label="Tujuan Khusus" value={f.tujuanKhusus} onChange={v=>set('tujuanKhusus',v)}/></Section>
 <Section title="4. Pemetaan Kondisi Awal"><Area label="Kondisi/Kebutuhan Awal" value={f.kondisi} onChange={v=>set('kondisi',v)}/><Area label="Prioritas Pendampingan" value={f.prioritas} onChange={v=>set('prioritas',v)}/></Section>
 <Section title="5–7. Sasaran, Materi & Strategi"><Area label="Sasaran" value={f.sasaran} onChange={v=>set('sasaran',v)}/><Area label="Materi" value={f.materi} onChange={v=>set('materi',v)}/><Area label="Strategi/Metode" value={f.strategi} onChange={v=>set('strategi',v)}/></Section>
 <Section title="8. Rencana Kegiatan"><div className="overflow-x-auto"><table className="table-clean text-xs"><thead><tr>{['Tahap','Kegiatan','Waktu','Metode','Sasaran','Indikator','Eviden',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{f.kegiatan.map((x,i)=><tr key={i}>{['tahap','kegiatan','waktu','metode','sasaran','indikator','eviden'].map(k=><td key={k}><textarea className="input min-w-[130px]" rows="3" value={x[k]} onChange={e=>row(i,k,e.target.value)}/></td>)}<td><button className="btn-danger btn-sm" onClick={()=>set('kegiatan',f.kegiatan.filter((_,n)=>n!==i))}>×</button></td></tr>)}</tbody></table></div><button className="btn-ghost mt-3" onClick={addRow}>＋ Tambah Kegiatan</button></Section>
 <Section title="9–10. Indikator, Eviden & Pengesahan"><Area label="Indikator Keberhasilan Program" value={f.indikator} onChange={v=>set('indikator',v)}/><Field label="Folder Eviden Google Drive" value={f.driveUrl} onChange={v=>set('driveUrl',v)} placeholder="https://drive.google.com/..."/></Section></div>}
 <div className="print-area card-pad bg-white"><PrintHeader settings={state.settings} judul="PROGRAM PENDAMPINGAN PENGAWAS"/><h2 className="text-center font-bold font-serif mb-4">{f.nama}</h2><Info label="Madrasah Sasaran" value={madrasah?.nama||'-'}/><Info label="Pengawas Pendamping" value={pengawas?.nama||'-'}/><Info label="Tahun/Semester" value={`${f.tahun} / ${f.semester}`}/><Info label="Periode" value={period}/><Doc title="A. Latar Belakang" text={f.latar}/><Doc title="B. Dasar Hukum" text={f.dasar}/><Doc title="C. Tujuan Umum" text={f.tujuanUmum}/><Doc title="D. Tujuan Khusus" text={f.tujuanKhusus}/><Doc title="E. Pemetaan Kondisi Awal" text={f.kondisi}/><Doc title="F. Prioritas Pendampingan" text={f.prioritas}/><Doc title="G. Sasaran" text={f.sasaran}/><Doc title="H. Materi Pendampingan" text={f.materi}/><Doc title="I. Strategi/Metode" text={f.strategi}/><h3 className="font-bold mt-5 mb-2">J. Rencana Kegiatan</h3><table className="table-clean text-[10px]"><thead><tr><th>No</th><th>Tahap/Kegiatan</th><th>Waktu</th><th>Metode</th><th>Sasaran</th><th>Indikator</th><th>Eviden</th></tr></thead><tbody>{f.kegiatan.map((x,i)=><tr key={i}><td>{i+1}</td><td><b>{x.tahap}</b><br/>{x.kegiatan}</td><td>{x.waktu}</td><td>{x.metode}</td><td>{x.sasaran}</td><td>{x.indikator}</td><td>{x.eviden}</td></tr>)}</tbody></table><Doc title="K. Indikator Keberhasilan" text={f.indikator}/>{f.driveUrl&&<p className="mt-3 text-xs"><b>Folder Eviden:</b> {f.driveUrl}</p>}<PrintSignature settings={state.settings} namaPengawas={pengawas?.nama} nipPengawas={pengawas?.nip}/></div></>
}
function Section({title,children}){return <div className="card-pad"><h2 className="font-semibold text-navy-900 mb-3">{title}</h2><div className="space-y-3">{children}</div></div>}
function Field({label,value,onChange,type='text',options=[],placeholder}){return <div><label className="label">{label}</label>{type==='select'?<select className="input" value={value||''} onChange={e=>onChange(e.target.value)}><option value="">— Pilih —</option>{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>:<input className="input" type={type} value={value||''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}</div>}
function Area({label,value,onChange}){return <div><label className="label">{label}</label><textarea className="input" rows="4" value={value||''} onChange={e=>onChange(e.target.value)}/></div>}
function Info({label,value}){return <p className="text-sm"><span className="inline-block w-44 font-semibold">{label}</span>: {value}</p>}
function Doc({title,text}){return <section className="mt-4"><h3 className="font-bold mb-1">{title}</h3><p className="whitespace-pre-line text-justify">{text}</p></section>}



