import { useEffect, useMemo, useState } from 'react'
import PageHeader from '../components/PageHeader.jsx'
import { useToast } from '../context/ToastContext.jsx'
import { printPrintArea } from '../lib/printHelper.js'
import { sourceBlocks } from '../data_programDokumen.js'

const KEY='kbc_program_pendampingan_full_v1'
const titles=['Sampul','Kata Pengantar','Lembar Pengesahan','Daftar Isi','BAB I — Pendahuluan','BAB II — Konsep Dasar KBC','BAB III — Desain Program Pendampingan','BAB IV — Strategi, Metode, dan Instrumen','BAB V — Rencana Operasional','BAB VI — Pelaporan, Aplikasi, dan Tindak Lanjut','BAB VII — Penutup','Daftar Rujukan','Lampiran 1 — Identitas Madrasah Piloting','Lampiran 2 — Jadwal Pendampingan','Lampiran 3 — Catatan Hasil Pendampingan','Lampiran 4 — Daftar Hadir','Lampiran 5 — Berita Acara','Lampiran 6 — Rekap Eviden KBC','Lampiran 7 — Rekomendasi dan RTL','Lampiran 8 — Rekap Capaian KBC','Lampiran 9 — Instrumen Monitoring','Lampiran 10 — Laporan Singkat']
const starts=['DOKUMEN PROGRAM','KATA PENGANTAR','LEMBAR PENGESAHAN','DAFTAR ISI','BAB IPENDAHULUAN','BAB IIKONSEP','BAB IIIDESAIN','BAB IVSTRATEGI','BAB VRENCANA','BAB VIPELAPORAN','BAB VIIPENUTUP','DAFTAR RUJUKAN','Lampiran 1.','Lampiran 2.','Lampiran 3.','Lampiran 4.','Lampiran 5.','Lampiran 6.','Lampiran 7.','Lampiran 8.','Lampiran 9.','Lampiran 10.']
function template(){const out=[];let active=-1;sourceBlocks.forEach(text=>{const hit=starts.findIndex(x=>text.startsWith(x));if(hit>=0)active=hit;if(active>=0){if(!out[active])out[active]={id:`section-${active+1}`,title:titles[active],content:''};out[active].content+=(out[active].content?'\n\n':'')+text}});return out.filter(Boolean)}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:template()}catch{return template()}}
export default function ProgramPendampinganPage(){
 const toast=useToast(),[sections,setSections]=useState(load),[selected,setSelected]=useState(0),[preview,setPreview]=useState(false)
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(sections)),[sections])
 const current=sections[selected];const words=useMemo(()=>sections.reduce((n,s)=>n+s.content.trim().split(/\s+/).filter(Boolean).length,0),[sections])
 const patch=(k,v)=>setSections(a=>a.map((s,i)=>i===selected?{...s,[k]:v}:s));const add=()=>{setSections(a=>[...a,{id:crypto.randomUUID(),title:'Bagian Baru',content:''}]);setSelected(sections.length)}
 const reset=()=>{if(confirm('Reset seluruh perubahan ke template asli DOCX?')){setSections(template());setSelected(0);toast.success('Template berhasil direset.')}}
 const word=()=>{const html=document.querySelector('.program-document')?.innerHTML||'';const blob=new Blob([`<html xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><style>${docCss}</style></head><body>${html}</body></html>`],{type:'application/msword'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Program-Pendampingan-KBC-Lengkap.doc';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast.success('Dokumen Word lengkap diunduh.')}
 return <><PageHeader title="Program Pendampingan Pengawas" icon="📘" description={`${sections.length} bagian • ${words.toLocaleString('id-ID')} kata • tersimpan otomatis`} actions={<><button className="btn-ghost" onClick={()=>setPreview(!preview)}>{preview?'✏️ Editor':'👁️ Preview'}</button><button className="btn-ghost" onClick={reset}>↺ Reset Template</button><button className="btn-ghost" onClick={()=>printPrintArea({title:'Program Pendampingan KBC'})}>🖨️ PDF</button><button className="btn-primary" onClick={word}>📄 Word</button></>}/>
 {!preview&&<div className="program-editor"><aside className="program-nav card-pad"><div className="font-semibold mb-3">Daftar Bagian</div>{sections.map((s,i)=><button key={s.id} className={`program-nav-item ${i===selected?'active':''}`} onClick={()=>setSelected(i)}><span>{i+1}</span>{s.title}</button>)}<button className="btn-ghost w-full mt-3" onClick={add}>+ Tambah Bagian</button></aside><main className="card-pad min-w-0">{current&&<><label className="label">Judul bagian</label><input className="input text-lg font-semibold mb-4" value={current.title} onChange={e=>patch('title',e.target.value)}/><div className="flex justify-between"><label className="label">Isi lengkap (bebas diedit)</label><small>{current.content.length.toLocaleString('id-ID')} karakter</small></div><textarea className="input program-textarea" value={current.content} onChange={e=>patch('content',e.target.value)}/><div className="flex justify-between mt-3"><button className="btn-danger" onClick={()=>{if(confirm('Hapus bagian ini?')){setSections(a=>a.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1))}}}>Hapus Bagian</button><span className="text-xs text-slate-500">Perubahan tersimpan otomatis di perangkat ini.</span></div></>}</main></div>}
 <div className={`${preview?'':'print-only'} print-area program-document`}>{sections.map((s,i)=><section className={`doc-page ${i===0?'cover-page':''}`} key={s.id}><h1>{s.title}</h1>{s.content.split(/\n\n+/).map((p,n)=>{const tableish=/^(No|Kode|Komponen|Pihak|Skor|Rentang)/.test(p)&&p.length>100;return tableish?<div className="doc-table-text" key={n}>{p}</div>:<p key={n}>{p}</p>})}</section>)}</div>
 </>
}
const docCss=`body{font-family:'Times New Roman',serif;color:#111}h1{text-align:center;font-size:16pt;margin:0 0 24px;text-transform:uppercase}p{font-size:12pt;line-height:1.5;text-align:justify;white-space:pre-wrap;margin:0 0 12px}.doc-page{page-break-before:always;padding:20mm}.doc-page:first-child{page-break-before:auto}.cover-page{min-height:240mm;display:flex;flex-direction:column;justify-content:center;text-align:center}.cover-page p{text-align:center}.doc-table-text{border:1px solid #555;padding:10px;font-size:10.5pt;line-height:1.45;white-space:pre-wrap;margin:12px 0}`
